/* import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
 */

import React,{useContext, useEffect, useState} from 'react'
import { Context } from '../context'
import TextField from '@mui/material/TextField';

import Router from 'next/router'
import axios from 'axios'
import { Button } from '@mui/material';
import ArrowBack from '@mui/icons-material/ArrowBack';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import QuestionMarkIcon from '@mui/icons-material/QuestionMark';
import Link from 'next/link';
import CheckCircleOutlineIcon from '@mui/icons-material/CheckCircleOutline';
import DangerousIcon from '@mui/icons-material/Dangerous';
import ReportGmailerrorredIcon from '@mui/icons-material/ReportGmailerrorred';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
function Auth() {
const {userName,
  setUserName,
  secret,
  setSecret}=useContext(Context)

const [pass,setPass]=useState<string>("")
const [pass_status,set_pass_status]=useState<null|string>(null)
//var changepass=false
  useEffect(()=>{
    console.log("username",userName)
    
  },[userName])
  
  useEffect(()=>{
    
    console.log("secret",secret)
    console.log("pass",pass)
                if(pass!==secret ||pass==='')
        {
            console.log("Passwords don't match")
            set_pass_status("unmatched")
            console.log("pass_status",pass_status)

        }
        else{
            console.log("Passwords matched")
            set_pass_status("matched")
            console.log("pass_status",pass_status)
        }
  },[secret,pass,pass_status])
  
  useEffect(()=>{
    if(secret===pass && pass!=""){
        set_pass_status("matched")
    }
    else{
        set_pass_status("unmatched")
    }
  },[secret,pass])

  return (
    <div className='background'>
      <div className='auth-container'>
        <form className='auth-form' onSubmit={e=>e.preventDefault()}>
          <div className='auth-title text-title ' style={{width:'95%',marginLeft:'2.5%'}}>WhosApp

          </div>
          {/* <div className='input_container'>
            <input placeholder='Enter Email' className='text-input'/>
          </div> */}

          <div className='login-buttons' style={{marginBottom:'4%'}}>
      <div style={{margin:5}}></div>

            <Link href='/' passHref><Button className='white-font-buttons'>
            <ArrowBack></ArrowBack>Sign In
            </Button></Link>
      <div style={{margin:5,}}></div>

            <Button className='white-font-buttons ' disabled={true} style={{backgroundColor:'white',fontWeight:'900',color:'black'}}>Register</Button>
      <div style={{margin:5}}></div>

          </div>


          <div style={{color:'white' ,backgroundColor:'hsla(136, 89%, 91%,0.85)',borderRadius:15,padding:5,paddingLeft:15,paddingRight:15,borderColor:'blue',borderWidth:5}}>
          <TextField sx={{color:'warning.main',width:1}} id="email" label="Enter Email" variant="standard" color="primary" type="email" onChange={(e)=>{setUserName(e.target.value)}}></TextField>
          </div>



          {/* <TextField
  label="Standard warning"
  variant="standard"
  color="warning"
  
/> */}
  <div style={{margin:'2.5%'}}></div>
  <div style={{color:'white' ,backgroundColor:'hsla(136, 89%, 91%,0.85)',borderRadius:15,padding:5,paddingLeft:15,paddingRight:15,borderColor:'blue',borderWidth:5}}>
            <TextField sx={{color:'warning.main',width:1}} id="password" label="Enter Password" variant="standard" color="primary" type="password" onChange={(e)=>{
                setSecret(e.target.value)
                
                }}/>

          </div>
  <div style={{margin:'2.5%'}}></div>

    <div className='row' style={{backgroundColor:'hsla(136, 89%, 91%,0.85)',borderRadius:15,}}>
        <div style={{color:'white' ,padding:5,paddingLeft:15,paddingRight:15,borderColor:'blue',borderWidth:5,width:'100%'}}>
        <TextField sx={{color:'warning.main',width:1}} id="repeat-password" label="Repeat Password" variant="standard" color="primary" type="password" 
        onChange={(e)=>{
            setPass(e.target.value)
        if(secret!==e.target.value)
        {
            console.log("Passwords don't match")
            set_pass_status("unmatched")
        }
        else{
            console.log("Passwords matched")
            set_pass_status("matched")

        }
        }}/>
        </div> 
{pass!=''&& pass_status==='matched'?<p style={{color:'green'}}><CheckCircleIcon>
    </CheckCircleIcon></p>:<></>}
    {pass==='' && secret !=""?<p style={{color:'orange'}}><ReportGmailerrorredIcon >
    </ReportGmailerrorredIcon></p>:<></>}
    { pass!=''&&pass_status==='unmatched'?<p style={{color:'red'}}><DangerousIcon>
    </DangerousIcon></p>:<></>}
    </div>



    <div className="row" style={{marginTop:'-4%'}}>
      <div className='enter-button-container' >
      <Button className='enter-button'>
        <div>Register</div>
        <ArrowForwardIcon fontSize='medium'></ArrowForwardIcon>
      </Button>
      </div>
      <div style={{margin:5}}></div>
      <Link href={'/forgot_password'} passHref>
        <div className='forgot-button-container'>
            <Button className='forgot-button'>
                <div>Forgot Password?</div>
                <ArrowForwardIcon></ArrowForwardIcon>
                {/* <QuestionMarkIcon fontSize='small'></QuestionMarkIcon> */}
            </Button>
        </div>
      </Link>
    </div>
        </form>
      </div>
      
    </div>
  )
}

export default Auth
